EDTTool/EDTT

- src/tests/ll_verification.py
Fix PB Flags used in LL/CON/MAS/BV-04-C, LL/CON/SLA/BV-05-C
and LL/CON/SLA/BV-06-C tests.
Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>
> Fix PB flags

- src/components/addata.py
- src/components/address.py
- src/components/attdata.py
- src/components/basic_commands.py
- src/components/edttt_bsim.py
- src/components/pairing.py
- src/components/preambles.py
- src/components/utils.py
- src/edttool.py
- src/tests/gap_verification.py
- src/tests/gatt_verification.py
- src/tests/hci_verification.py
- src/tests/le_transceiver_test.py
- src/tests/ll_multiple_connections.py
- src/tests/ll_verification.py
Convert the Python codebase to Python 3, including all test
implementations.
Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>
> Convert to Python 3

- src/tests/ll_verification.py
The pass verdict is "All bits in the feature set marked as Masked to
Peer received by the Lower Tester are cleared. The test procedure is
executed successfully, with the IUT responding with the feature
response." Identity between feature sets is not needed for passing.
> Align LL/CON/MAS/BV-23-C with test specification

- src/tests/ll_verification.py
The Bluetooth test spec requires a remote feature  exchange procedure to be executed at the start of the DLE related tests. This is added in this PR.
This will break the DLE related tests, which requires a fix in the zephyr code base, but these tests also fail in EBQ.
Note a lot of white space changes due to removal of single space at EOL.
Signed-off-by: Andries Kruithof <Andries.Kruithof@nordicsemi.no>
> Add call to feature exchange procedure before executing the DLE procedure

- src/tests/ll_verification.py
If the target app does not support slave-initiated feature exchange
the following tests will fail:
LL/CON/SLA/BV-77-C
LL/CON/SLA/BV-78-C
LL/CON/SLA/BV-80-C
LL/CON/SLA/BV-81-C
To fix this replace with master-initiated feature exchange.
Signed-off-by: Thomas Ebert Hansen <thoh@oticon.com>
> Use master-initiated feature exchange in DLE procedure

- src/tests/ll_verification.py
Unicode chars in the test descrition can cause problems depending on
how shell and Python is setup.
Signed-off-by: Lars Marqvart Joergensen <lmjo@oticon.com>
> Convert all Unicode dashes (\u2013) to ASCII '-'

- src/tests/ll_verification.py
Fix issues discovered in the EDTT tests.
> Fix test issues

- src/tests/gap_verification.py
- src/tests/gatt_verification.py
- src/tests/hci_verification.py
Fix use of the invalid disconnect reason 0x3e "connection failed to
be established", which is not valid in the Disconnect command.
Use the more appropriate reason 0x13 "remote user terminated
connection"
Update for GAP, GATT and HCI test cases, LL has already been updated.
Follow up to : https://github.com/EDTTool/EDTT/pull/20
> Fix use of invalid disconnect reason in test procedures

- src/tests/ll_verification.py
Fix some SLA tests that used upperTester as initiator, to
use the lowerTester. The issue was noticed when running
two different build configured hci application as IUT and
TST, wherein IUT was a peripheral only controller and TST
was full feature HCI controller. In this case, using the
upperTester as initiator failed, which is incorrect usage
in these tests.
Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>
> Fix some SLA tests to use lowerTester as initiator

- src/components/initiator.py
Increase the number of connection interval events to wait
for the LE Connection Parameter Request Procedure to timeout.
Zephyr controller implementation is changed so that LE
Connection Parameter Request, Connection Parameter Response,
and Connection Update Indication PDUs are enqueued after
the offsets have been successfully calculated, which will
take an additional connection interval to enqueue the PDU.
Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>
> Increase Connection Parameter Request Procedure Timeout

- src/components/advertiser.py
- src/components/basic_commands.py
- src/components/initiator.py
- src/components/preambles.py
- src/components/scanner.py
- src/edttool.py
- src/tests/ll_verification.py
It has been seen for a while, that changing the order of the LL-tests could make quite a number of tests fail now and again.
During debugging of this, I found the below mentioned error in the address scrambling as well as the error in the has_event util function.
Address scramble utils fixed - previous version swapped bytes in
address to create new address, this fails if bytes are identical
has_event util timeout handling was incorrect - waited longer. Now
the timeout is correct. However this then calls for the general update
to timeouts.
Added formatted timing info to trace-out
> Fixing address scramble issue, as well as misc. timing related issues

- src/components/basic_commands.py
- src/components/events.py
The following ISO HCI events have been added:
- BT_HCI_EVT_LE_CIS_ESTABLISHED
- BT_HCI_EVT_LE_CIS_REQUEST
The following ISO HCI commands have been added:
- le_set_cig_parameters
- le_set_cig_parameters_test
- le_create_cis
- le_remove_cig
- le_accept_cis_request
- le_reject_cis_request
- le_setup_iso_data_path
- le_remove_iso_data_path
- le_set_host_feature
The following ISO EDTT commands have been added:
- le_iso_data_flush
- le_iso_data_ready
- le_iso_data_write
- le_iso_data_read
Signed-off-by: Morten Priess mtpr@oticon.com
> Added support for ISO EDTT/HCI commands and ISO HCI events

- src/tests/hci_verification.py
- src/tests/ll_verification.py
Relates to: https://github.com/zephyrproject-rtos/zephyr/pull/38407
Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>
> Fix Data Length Procedure tests to skip IUT unsupported parameters

- src/tests/test_utils.py
Trying to read ISO data before it is available throws an
exception. Therefore, le_iso_data_ready() needs to be checked before
calling le_iso_data_read().
> Wait for ISO data to be ready before reading

- src/components/basic_commands.py
- src/components/events.py
- src/tests/ial_verification.py
- src/tests/ll_verification.py
- src/tests/test_utils.py
Handle fragmentation of ISO SDUs over HCI by splitting data according
to the available buffer size and waiting for the respective number of
packets to be completed. Includes the addition of the LE Read Buffer
Size [v2] command and a minor fix to ensure that the SDU size does not
exceed the PDU size for some test cases.
> Handle fragmentation of ISO SDUs over HCI for transmission

- src/components/initiator.py
When initiating a disconnect, another event may occur before we
get the disconnection complete event.
For example the PHY Update complete event.
If this happens, we should still be able to disconnect properly.
Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>
> initiator: Fix disconnect with other event at the same time

- src/components/dump.py
- src/components/initiator.py
- src/components/preambles.py
- src/tests/ll_verification.py
Added the two test cases
Updated PacketDecoder to support a lot more packets and added a flush() to clear out any existing packets when looping inside a test case
Updated Initiator to support connecting via extended commands
> Add LL/CON/ADV/BV-14-C and LL/CON/ADV/BV-15-C test cases

- src/components/basic_commands.py
- src/tests/ll_verification.py
Added tests for LL/CON/ADV/BV-05-C and LL/CON/ADV/BV-12-C; Note that the implementation is only partial, since we cannot control the contents of AUX_CONNECT_REQ directly
Fixed le_extended_create_connection() commands handling of non-1M phys
> Add LL/CON/ADV/BV-05-C and LL/CON/ADV/BV-12-C test cases

- src/tests/test_utils.py
Original behavior was indeed correct.
This reverts commit ffe55d0c6fa427685e4268ae8f418772f602f9b7.
> Revert "Fix handling of HCI ISO data fragment headers"

- src/tests/test_utils.py
The users of le_iso_data_write_nbytes wait for the completion of the writes, trying to wait twice causes timeouts.
> Skip waiting for completion in le_iso_data_write_nbytes

- docs/EDTT_transport_bsim.md
- src/components/edttt_bsim.py
The EDTT bridge will now reply to wait commands; Read this reply before returning from transport.wait()
> Wait for reply to wait command

- src/components/preambles.py
- src/tests/ll_verification.py
Enabled existing test for LL/DDI/ADV/BV-21-C extended advertising with legacy PDUs, non-connectable and fixed minor issues.
Signed-off-by: Nirosharn Amarasinghe <niag@demant.com>
> Enabled LL/DDI/ADV/BV-21-C and fixed issues

- src/components/bsim_lib.py
One return in test_and_create_lock_file() was missing the path
> Fix missing removal of the low level devices lockfile

- src/components/dump.py
- src/components/events.py
- src/tests/ll_verification.py
Added the two (very similar) test cases
Updated packet trace decoding, so extended advertisement packets will now have a pointer to its superior packet(s)
Fixed decoding of the LE Advertising Set Terminated event when advertising has stopped to some other cause than a new connection
Signed-off-by: Troels Nilsson [trnn@demant.com](mailto:trnn@demant.com)
> Add LL/DDI/ADV/BV-47-C and LL/DDI/ADV/BV-49-C test cases

- src/components/dump.py
- src/tests/ll_verification.py
Adds the LL/DDI/ADV/BV-28-C test case
Fix packets.flush not flushing packets that are still unread
Signed-off-by: Troels Nilsson [trnn@demant.com](mailto:trnn@demant.com)
> Add LL/DDI/ADV/BV-28-C test case

- src/tests/ll_verification.py
- src/tests/test_utils.py
Adds the LL/DDI/ADV/BV-27-C test case to ll_verification.py
Signed-off-by: Troels Nilsson [trnn@demant.com](mailto:trnn@demant.com)
> Add LL/DDI/ADV/BV-27-C test case

- src/components/edttt_bsim.py
Python would on rare occasions try to open the files before the 2G4 phy had opened/created them, causing weird errors
Fixed by blocking the transports connect() until the phy has been confirmed to be ready
> Fix race when opening BSim dump files

- docs/EDTT_transport_bsim.md
- src/components/edttt_bsim.py
Use the new WAIT_WRESP command to the EDTT bridge instead of the November modified WAIT when expecting a reply for a wait command.
The change in the WAIT command functionality
broke backwards compatibility with the EDTT bridge (and backwards compatibility from the newer bridge to older EDTT version).
The bridge has now been fixed to avoid the backwards compatibility issue with older (prior to Nov/23,
18744c937131104797ea0abf0dcfc84855a12311
) versions of the EDTT, but this means the WAIT
command no longer responds. Instead we need to use the new WAIT_WRESP command.
Also check the response, if we get a UNKNOWN_COMMAND (or anything !=0), we warn the user about the too old EDTT instead of crashing badly.
Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
> bsim transport: Use WAIT_WRESP insteado of WAIT

- src/components/dump.py
- src/tests/ll_verification.py
- src/tests/test_utils.py
Adds the (very similar) LL/DDI/ADV/BV-45-C and LL/DDI/ADV/BV-52-C test cases
Adds a few new functions to test_utils.py for code snippets that are now in use in several places
Fix some extended advertising decoding in dump.py:
- Add AUX_SCAN_RSP packets to __aux_ptr_packets
- Fix parsing of packets with an extended header length of 0
> Add LL/DDI/ADV/BV-45-C and LL/DDI/ADV/BV-52-C test cases

- src/components/edttt_bsim.py
Handle more gracefully when the Phy disconnects us or when it disapears.
In short: Once the phy tells us to disconnect, we cannot send anything back. Similarly be sure that an exception on __disconnect does not lead to an infinite loop of cleanups and exceptions
> edttt_bsim: Avoid infinite exception loop

- src/tests/ll_verification.py
- src/tests/test_utils.py
* Use correct handle in cis_setup_procedure_central_initiated.
* Trigger feature exchange before establishing CIS to avoid long control PDUs being truncated.
> Fix some issues found during CIS Central testing

- src/tests/ll_verification.py
According to LL.TS.p23 the ISO interval for this test should be 100ms.
> Corrected ISO interval for LL/CIS/PER/BV-05-C
